# Generated by Django 4.0.3 on 2022-03-11 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('length', models.PositiveIntegerField(default=0)),
                ('lengthHM', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startRoutineTime', models.DateTimeField()),
                ('startFallingAsleepTime', models.DateTimeField()),
                ('finishTime', models.DateTimeField()),
                ('isItNightSleep', models.BooleanField(default=False)),
                ('place', models.CharField(max_length=255)),
                ('moodStartOfSleep', models.CharField(max_length=255)),
                ('moodEndOfSleep', models.CharField(max_length=255)),
                ('segments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.segment')),
            ],
        ),
    ]
