# Generated by Django 4.0.3 on 2022-04-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='sleep',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='sleep',
            name='moodEndOfSleep',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='moodStartOfSleep',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
