# Generated by Django 4.0.3 on 2022-04-03 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_sleep_segments_sleep_segments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleep',
            name='segments',
        ),
        migrations.AddField(
            model_name='sleep',
            name='segments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.segment'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('sleeps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.sleep')),
            ],
        ),
    ]
