# Generated by Django 4.0.3 on 2022-04-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_sleep_segments_sleep_segments_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
