# Generated by Django 4.0.3 on 2022-06-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('client', 'Client'), ('consultant', 'consultant')], default='client', max_length=64)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='is confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='first name')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='patronymic')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='surname')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, verbose_name='date of birth')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='user photo')),
                ('note', models.TextField(blank=True, null=True)),
                ('enable', models.BooleanField(blank=True, null=True)),
                ('langs', models.ManyToManyField(blank=True, to='authentication.language', verbose_name='languages')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-id'],
            },
        ),
    ]
