# Generated by Django 4.0.3 on 2022-06-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('client', 'Client'), ('consultant', 'Consultant')], default='client', max_length=64),
        ),
    ]
